### ISSUE TITLE
download the code and run example.py, it will fail

### ISSUE THREAD

**Issue by GlobalMe2017** [ultrafunkamsterdam/undetected-chromedriver#2259]
it is my first time to use uc,  is there anyone could help? thanks.

so i download the code from git, 

run installation
`pip install undetected-chromedriver`

then run the example.py, then it failed as below, 

```
C:\ProgramData\anaconda3\python.exe C:/Users/Administrator/PycharmProjects/undetected-chromedriver-master/example/example.py
DEBUG:undetected_chromedriver.patcher:getting release number from /last-known-good-versions-with-downloads.json
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\undetected-chromedriver-master\example\example.py", line 181, in <module>
    main(a)
  File "C:\Users\Administrator\PycharmProjects\undetected-chromedriver-master\example\example.py", line 29, in main
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Users\Administrator\PycharmProjects\undetected-chromedriver-master\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\Administrator\PycharmProjects\undetected-chromedriver-master\undetected_chromedriver\patcher.py", line 177, in auto
    self.version_main = release.version[0]
                        ^^^^^^^^^^^^^^^
AttributeError: 'Version' object has no attribute 'version'. Did you mean: '_version'?
INFO:uc:ensuring close
```

my python is anaconda python 3.10

**Comment by utam-1** [comment]
Hi @GlobalMe2017, try explicitly specifying your chrome's major version as follows : – 
1. Open your Chrome browser -----> Click on ⋮ (for menu) ------->  Settings -------> Scroll all the way down to find About Chrome.
2.  You will find something like – Version : 128.0.6613.138.
3.  The major version in this case is 128.

Then try changing the Line 27 in example.py as follows : – `driver = uc.Chrome(version_main= chrome_major_version) # replace chrome_major_version with the version you see`

Let me know how it goes for you

**Comment by XaapX** [comment]
Had the same issue that popped very recently (When upgrading selenium from 4.34.2-1 to 4.38.0-1 on Arch)
I can confirm @dustinfarris patch works (with a trivial rebase for current master)
Thanks
